name: PR check
on:
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    environment: 'LOCAL'

    steps:
    - uses: actions/checkout@v4

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9.8.0

    - uses: actions/setup-node@v4
      with:
        node-version: 20.17.0
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Install Playwright Browsers
      run: pnpm dlx playwright install --with-deps

    - name: Verify Environment Variables
      run: echo $DATABASE_URL

    - name: Run database create .env file
      run: | 
        echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > ./packages/database/.env
        echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" > ./packages/database/.env
        echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" > ./packages/database/.env
        echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" > ./packages/database/.env

    - name: Run Database
      run: |
            pnpm exec turbo db:start
            PRISMA_DOTENV_PATH=./packages/database/.env pnpm exec turbo db:migrate
            PRISMA_DOTENV_PATH=./packages/database/.env pnpm exec turbo db:seed
        
    - name: Run Unit tests
      run: pnpm exec turbo test

    - name: Run E2E tests
      run: pnpm exec turbo e2e:run

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30