name: PR check
on:
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9.8.0

    - uses: actions/setup-node@v4
      with:
        node-version: 20.17.0
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Run Project
      run: pnpm exec turbo dev

    - name: Run Unit tests
      run: pnpm exec turbo test

    - name: Install Playwright Browsers
      run: pnpm exec playwright install --with-deps

    - name: Run E2E tests
      run: pnpm exec turbo e2e:run

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30